import React, { useState } from "react";
import Head from "next/head";
import { css, cx } from "@emotion/css";
import H2 from "../../Component/Typography/H2";
import InputEmail from "../../Component/InputEmail";
import InputPassword from "../../Component/InputPassword";
import Button from "../../Component/Button";
import FormContorol from "../../Component/FormContorol/FormContorol";
import Space from "../../Component/Typography/Space";
import Link from "next/link";
import HyperLink from "../../Component/Hyperlink/HyperLink";

export default function Login() {
  const [valueFrom, setValueFrom] = useState({});
  const handelForm = (e) => {
    if (e) e.preventDefault();
    console.log("handelForm", valueFrom);
  };
  const handelOnChange = (name, value) => {
    setValueFrom({ ...valueFrom, [name]: value });
  };

  return (
    <>
      <Head>
        <title> بازیابی کلمه عبور </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={css`
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        `}
      >
        <img
          className={css`
            height: 350px;
          `}
          src="Logo.png"
          alt="img_login"
        />

        <H2 align="center">فراموش کار شدی ؟</H2>
        <form
          onSubmit={handelForm}
          className={css`
            display: flex;
            flex-direction: column;
            align-content: center;
            justify-content: center;
            align-items: center;
            width: 350px;
          `}
        >
          <FormContorol>
            <InputEmail
              placeholder="ایمیل خود را وارد کنید"
              autoFocus={true}
              onChange={(value) => handelOnChange("Email", value)}
            />
          </FormContorol>
          <Space />

          <Space />
          <FormContorol>
            <Button type="submit">ارسال</Button>
          </FormContorol>
        </form>
        <div>
          <HyperLink href="/login">وارد شوید</HyperLink>
        </div>
        <div>
          <HyperLink href="/register">ثبت نام</HyperLink>
        </div>
      </div>
    </>
  );
}
