import React from "react";
import Head from "next/head";
import CardProdoctLIst from "../../Component/CardProdoctLIst";

const checkout = () => {
  return (
    <div>
      <Head>
        <title>سبد خرید </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CardProdoctLIst />
    </div>
  );
};

export default checkout;
