const actionTypes = {
    LOGIN_STARTED: "LOGIN_STARTED",
    LOGIN_SUCCES: "LOGIN_SUCCES",
    LOGIN_FAILD: "LOGIN_STARTED",
    //----------------------------------
    LOAD_COURSES_STARTED: "LOAD_COURSES_STARTED",
    LOAD_COURSES_SUCCES: "LOAD_COURSES_SUCCES",
    LOAD_COURSES_FAILD: "LOAD_COURSES_STARTED",
    //----------------------------------
    ADD_COURSES_STARTED: "ADD_COURSES_STARTED",
    ADD_COURSES_SUCCES: "ADD_COURSES_SUCCES",
    ADD_COURSES_FAILD: "ADD_COURSES_STARTED",
};
export default actionTypes;