import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import getApi from "../utils/getApi";
import { css, cx } from "@emotion/css";
import store from "../configs/store";
import { LOAD_COURSES_ACTION } from "../actions";

const Home = () => {
  useEffect(() => {
    store.dispatch(LOAD_COURSES_ACTION());
  }, []);
  return (
    <div
      className={css`
        padding: 0 2rem;
      `}
    >
      <Head>
        <title> خانه </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <div
        className={css`
          min-height: 100vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        `}
      >
        <div> Home </div>{" "}
      </div>{" "}
    </div>
  );
};

// Home.getInitialProps = async ({ reduxStore }) => {
//   // console.log("reduxStore", reduxStore);
//   return {};
// };

export default Home;
