import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import getApi from "../utils/getApi";
import { css, cx } from "@emotion/css";
import store from "../configs/store";
import contentful from "../helpers/contentful";
import { LOAD_COURSES_ACTION } from "../actions";
import { useState } from "react";
import Link from "next/link";
import CardInfo from "../Component/CardInfo";

const Home = () => {
  return (
    <>
      <Head>
        <title> خانه </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[url('../public/bgImg.jpg')] w-full h-screen bg-cover bg-top mt-0 relative ">
        <div className="w-full h-full bg-black opacity-75 flex ">
          <div className="text-8xl text-cyan-50 flex flex-col justify-center h-full w-1/2 items-center">
            <div className="text-5xl text-cyan-50 flex flex-col justify-center w-full items-center">
              <div className=" p-5">
                <h4>آموزش پروژه محور برنامه نویسی </h4>
              </div>
              <div
                className={css`
                  padding: 20px;
                  font-size: 20px;
                  width: 50%;
                `}
              >
                <h4>پشتیبانی قدم به قدم | وبینار های رایگان </h4>
              </div>
              <div>
                <Link href={`/courses`}>
                  <a>
                    <button className=" rounded-lg pt-5 pb-5 pl-8 pr-8 transition-all ease-in bg-gradient-to-r from-purple-500 to-pink-500 cursor-pointer text-cyan-50 mt-5 hover:translate-x-6  ">
                      همین الان شروع کن
                    </button>
                  </a>
                </Link>
              </div>
            </div>
          </div>{" "}
        </div>
      </div>

      <CardInfo />
    </>
  );
};

// Home.getInitialProps = async ({ reduxStore }) => {
//   // console.log("reduxStore", reduxStore);
//   await reduxStore.dispatch(LOAD_COURSES_ACTION());
//   const { courses } = reduxStore.getState();
//   //   console.log("courses", courses);

//   return {
//     courses,
//   };
// };

export default Home;
