import React, { useState, useEffect } from "react";
import { useRouter } from "next/dist/client/router";
import { useSelector } from "react-redux";
import Head from "next/head";
import contentful from "../../helpers/contentful";
import { v4 as uuidv4 } from "uuid";

import { css, cx } from "@emotion/css";

const coursePage = (props) => {
  const { entry } = props;

  return (
    <>
      <Head>
        <title>{entry.fields.titleProduct}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row h-screen  mt-5 ">
        <div className=" w-2/6 flex justify-center ">
          <div className=" w-3/6 bg-green-200 rounded-md h-5/6 p-10 overflow-auto ">
            <h3 className="text-2xl font-bold  ">سر فصل ها</h3>
            <div className="m-2 justify-center flex flex-wrap flex-row ">
              <p className="m-1 ">آموزش کامپوننت ها </p>
              <hr className=" bg-black opacity-100" />
              <p className=" m-1">آموزش پراپس</p>
            </div>
          </div>
        </div>
        <div className="w-4/6  h-5/6  ">
          <div className=" bg-green-200 h-full w-5/6  rounded-md overflow-y-scroll">
            <div>
              <img
                src={entry.fields.imgCard.fields.file.url}
                alt={entry.fields.titleProduct}
                className=" p-2 rounded-3xl"
              />
            </div>
            <div className=" m-3">
              <h3 className="text-3xl font-bold  ">
                {entry.fields.titleProduct}
              </h3>
            </div>
            <div>
              {entry.fields.aboutProduct.content.map((item) => (
                <p className="m-6 indent-4 " key={uuidv4()}>
                  {item.content[0].value}
                </p>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async (context) => {
  const id = context.req.url;
  const result = id.split("/");
  const arr = result.slice(-1)[0];
  const myUrl = arr.split("=");
  const query = myUrl.slice(-1)[0];

  // console.log(query);

  const data = await contentful
    .getEntries({
      content_type: "cardShop",
      "sys.id": query,
    })
    .catch(console.error);

  const [entry] = data.items;

  return { props: { entry } };
};

export default coursePage;
