import React from "react";
import { css, cx } from "@emotion/css";
import Head from "next/head";
import CardList from "../../Component/CardList/CardList";

import { useSelector } from "react-redux";

const Courses = () => {
  const courses = useSelector((state) => state.courses);
  console.log(courses.courses);

  return (
    <>
      <Head>
        <title> دوره های آموزشی </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={css`
          display: flex;
          width: 100%;
        `}
      >
        <CardList courses={courses.courses} />
      </div>
    </>
  );
};

export default Courses;
