import React, { useState, useEffect } from "react";
import { css, cx } from "@emotion/css";
import Head from "next/head";
import CardList from "../../Component/CardList/CardList";
import { LOAD_COURSES_ACTION } from "../../actions";
import { useSelector } from "react-redux";
import contentful from "../../helpers/contentful";
import Link from "next/link";

const Courses = () => {
  // console.log(props);
  const { courses } = useSelector((state) => state.courses);
  // console.log("courses", courses);
  // console.log("props", props);

  return (
    <>
      <Head>
        <title> دوره های آموزشی </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={css`
          display: flex;
          width: 100%;
          justify-content: center;
        `}
      >
        <CardList courses={courses} />
      </div>
    </>
  );
};
Courses.getInitialProps = async ({ reduxStore }) => {
  // console.log("reduxStore", reduxStore.getState());
  await reduxStore.dispatch(LOAD_COURSES_ACTION());
  // const { courses } = await reduxStore.getState();
  // console.log(courses);

  return {};
};

export default Courses;
